---
# tasks file for kops
- name: get the kops version
  shell: echo  $(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)
  register: myversion
- name: store version in variable
  set_fact: version={{ myversion.stdout }}
- name: install kops
  become: yes
  get_url:
    url: https://github.com/kubernetes/kops/releases/download/{{ version }}/kops-linux-amd64
    dest: /usr/local/bin/kops
    mode: 0777
